version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: localhost
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.11.60:9081'
        gitlab_rails['gitlab_shell_ssh_port'] = 2022
    ports:
      - 9081:9081
      - 2022:2022
    volumes:
      - /var/gitlab/config:/etc/gitlab
      - /var/log/gitlab:/var/log/gitlab
      - /var/gitlab/data:/var/opt/gitlab
  plantuml:
    image: plantuml/plantuml-server
    ports:
      - 18081:8080
  plantuml-materials:
    image: nginx
    volumes:
      - /var/plantuml-materials:/usr/share/nginx/html/
    ports:
      - 28080:80
